# gotchi/config.toml  ── minimal but functional defaults

[hw]
iface       = "wlan0"          # physical interface name

  [hw.hop]
  channels     = [1, 6, 11]    # default hop list
  interval_ms  = 400           # 0.4 s per hop

[attacks.deauth]
pps_limit    = 50              # max de-auth frames per second
burst_count  = 16              # packets per kick burst
mode         = "kick"          # or "flood"

[capture]
folder = "captures"

  [capture.rotate]
  max_size_mb = 10             # rotate at 10 MiB
  max_age_s   = 300            # …or 5 minutes, whichever first

[pipeline.crack]
auto      = false              # set true to launch hashcat automatically
wordlists = ["~/wordlists/rockyou.txt"]
