name: wifi_ap_captive_apache
group: network
summary: Host Wi‑Fi AP + DHCP/DNS and serve captive portal via Apache
harden: false
requirements: []   # we will NOT force USB; this is Wi‑Fi only
env:
  IFACE: wlan0
  SSID: P4wnP1_O2
  CHANNEL: "6"
  AP_NET: 10.20.0.1/24
  AP_RANGE_START: 10.20.0.100
  AP_RANGE_END: 10.20.0.200
preflight:
  - "systemctl stop wpa_supplicant || true"
  - "ip link set ${IFACE} down || true"
  - "ip addr flush dev ${IFACE} || true"
  - "ip addr add ${AP_NET} dev ${IFACE}"
  - "ip link set ${IFACE} up"
  - "apt-get update -y -qq"
  - "apt-get install -y -qq hostapd dnsmasq"
  - "cp -f /opt/p4wnp1/payloads/network/wifi/hostapd.conf /etc/hostapd/hostapd.conf"
  - "cp -f /opt/p4wnp1/payloads/network/wifi/dnsmasq_ap.conf /etc/dnsmasq.d/p4wnp1_ap.conf"
  - "sed -i \"s/^interface=.*/interface=${IFACE}/\" /etc/hostapd/hostapd.conf"
  - "sed -i \"s/^ssid=.*/ssid=${SSID}/\" /etc/hostapd/hostapd.conf"
  - "sed -i \"s/^channel=.*/channel=${CHANNEL}/\" /etc/hostapd/hostapd.conf"
  - "sed -i \"s/^interface=.*/interface=${IFACE}/\" /etc/dnsmasq.d/p4wnp1_ap.conf"
  - "sed -i \"s/^dhcp-range=.*/dhcp-range=${AP_RANGE_START},${AP_RANGE_END},255.255.255.0,12h/\" /etc/dnsmasq.d/p4wnp1_ap.conf"
  - "rfkill unblock wifi || true"
  - "systemctl restart dnsmasq"
  - "systemctl restart hostapd"
  # Captive “walled‑garden” DNS redir to Apache
  - "iptables -t nat -F PREROUTING || true"
  - "iptables -t nat -A PREROUTING -i ${IFACE} -p tcp --dport 80 -j DNAT --to-destination 10.20.0.1:80"
  - "iptables -t nat -A PREROUTING -i ${IFACE} -p tcp --dport 443 -j DNAT --to-destination 10.20.0.1:80"
  - "sysctl -w net.ipv4.ip_forward=1"
cmd: "echo 'AP up on ${IFACE}; captive portal should answer on 10.20.0.1'"
